### PR TITLE
A big PR to fix many things

### PR DESCRIPTION
**Pull request by ghost**
Please review individually,

### CODE REVIEW

**Comment by fizzyizzy05** [comment]
This all looks good and reasonable. LGTM. Thank you!

**Comment by fizzyizzy05** [comment]
I've added you to the Translator credits using the name you used on GitHub. Please let me know if you want this changed, or reverted. [1788dd3](https://github.com/fizzyizzy05/binary/commit/1788dd3244085796ed6b4ec165ffda8bc9fd7d91)

**Comment by ghost** [comment]
This string changes via the po files. Actually you have broken it.

https://github.com/fizzyizzy05/binary/blob/main/po/tr.po#L67-L70

**Comment by fizzyizzy05** [comment]
that's weird, without it the translation credits are empty:
image

**Comment by ghost** [comment]
it is locale centric and will be visible to corresponding language.

**Comment by fizzyizzy05** [comment]
Okay then, I'll revert this!

**Pull request merged**
